version: '3'
services:
  blue-backend:
    build:
      context: ../backend
    ports:
      - "8081:8081"
    environment:  # 환경 변수 추가 부분
      - SMS_KEY=NCSRGCEYXNITRXGO
      - SMS_SECRET_KEY=DJSA1XHJB6HMRZZHSARMBVTZ50SZCEJL
      - SENDER=01099509587

  blue-backend-mydata:
    build:
      context: ../backend-mydata
    ports:
      - "8082:8082"
