version: '3'
services:
  blue-backend:
    build:
      context: ../backend
    ports:
      - "8083:8081"
  blue-backend-mydata:
    build:
      context: ../backend-mydata
    ports:
      - "8084:8082"