spring:
  jpa:
    hibernate:
      ddl-auto: none #create update none
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        format_sql: true # 보여지는 쿼리를 예쁘게 포맷팅 -> 사용하지않으면 긴 줄 형태로 출력됌
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j9a610.p.ssafy.io:3306/benepick_bank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: benepick
    password: benepick
#    hikari:
#      maximum-pool-size: 20           #최대 pool size (defailt 10)
#      connection-timeout: 30000
#      minimum-idle: 10                #연결 풀에서 HikariCP가 유지 관리하는 최소 유휴 연결 수
#      idle-timeout: 600000            #연결을 위한 최대 유휴 시간
#      max-lifetime: 1800000           #닫힌 후 pool 에있는 connection의 최대 수명 (ms)입니다.

server:
  port: 8082
#  tomcat:
#    threads:
#      max: 300
#      min-spare: 10
#    max-connections: 8192
#    accept-count: 100
#    connection-timeout: 30000

# 로그 레벨 설정
#logging:
  #level:
    # hibernate 가 남기는 모든 로그가 debug모드로 설정
    # jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
    #org.hibernate.SQL: debug
    #org.hibernate.orm.jdbc.bind: trace
    #org.springframework.web.socket: trace

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus