spring:
  profiles: # profiles 설정
    active: dev # 다른 설정이 없을 때 default 환경 값

  jpa:
    hibernate:
      ddl-auto: create #create update none
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        format_sql: true # 보여지는 쿼리를 예쁘게 포맷팅 -> 사용하지않으면 긴 줄 형태로 출력됌

  cache:
    type: redis

  data:
    redis:
      host: j9a610.p.ssafy.io
      port: 6379
      timeout: 5000 # 서버와의 연결 시도 및 응답 대기 시간 최대 5초

server:
  port: 8080
  tomcat:
    threads:
      max: 300
      min-spare: 10
    max-connections: 8192
    accept-count: 100
    connection-timeout: 30000


    # 로그 레벨 설정
#logging:
  #level:
    # hibernate 가 남기는 모든 로그가 debug모드로 설정
    # jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
    #org.hibernate.SQL: debug
    #org.hibernate.orm.jdbc.bind: trace
    #org.springframework.web.socket: trace

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus